# Generated by Django 2.0.2 on 2018-03-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegeheld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtext',
            name='offense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wegeheld.Offense'),
        ),
    ]
