# Generated by Django 2.0.2 on 2018-04-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegeheld', '0002_auto_20180327_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('tmstmp', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('list_position', models.IntegerField(default=90)),
                ('deleted', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['list_position'],
            },
        ),
        migrations.AlterField(
            model_name='emailtext',
            name='template',
            field=models.TextField(max_length=16500),
        ),
        migrations.AlterField(
            model_name='publicaffairsoffice',
            name='postalcode',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='free_text',
            field=models.CharField(max_length=225),
        ),
        migrations.AddField(
            model_name='report',
            name='hinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wegeheld.Hinder'),
        ),
    ]
