# Generated by Django 2.0.2 on 2018-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegeheld', '0003_auto_20180414_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='free_text',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='report',
            name='tweet',
            field=models.CharField(blank=True, max_length=115),
        ),
    ]
