# Generated by Django 2.0.2 on 2018-04-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegeheld', '0004_auto_20180414_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hinder',
            new_name='Obstruction',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='hinder',
            new_name='obstruction',
        ),
        migrations.AlterField(
            model_name='funnysaying',
            name='valid_offenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wegeheld.Offense'),
        ),
        migrations.AlterField(
            model_name='publicaffairsoffice',
            name='postalcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
